# Generated by Django 5.0.1 on 2024-01-12 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yobbo_Api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yobboadmin',
            name='password',
            field=models.CharField(max_length=50, verbose_name='password'),
        ),
    ]
