# Generated by Django 5.0.1 on 2024-01-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yobbo_Api', '0002_alter_yobboadmin_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yobboadmin',
            name='password',
            field=models.CharField(max_length=255, verbose_name='password'),
        ),
    ]
