# Generated by Django 5.0.1 on 2024-01-12 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yobbo_Api', '0003_alter_yobboadmin_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yobboadmin',
            name='username',
        ),
    ]
