# Generated by Django 5.0.1 on 2024-01-13 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yobbo_Api', '0007_yobboadmin_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yobboadmin',
            name='username',
        ),
    ]
