# Generated by Django 5.0.1 on 2024-01-13 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Yobbo_Api', '0009_auto_20240113_1712'),
    ]

    operations = [
        migrations.AddField(
            model_name='yobboadmin',
            name='username',
            field=models.CharField(default='admin1', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
