# Generated by Django 5.0.1 on 2024-01-13 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yobbo_Api', '0010_yobboadmin_username'),
    ]

    operations = [
    ]
