# Generated by Django 5.0.1 on 2024-01-13 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Yobbo_Api', '0012_alter_yobboadmin_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='yobboadmin',
            managers=[
            ],
        ),
    ]
